### ISSUE TITLE
User Story: Authentication | Sign up

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#11]
As a **user** I can **create a new account** so that **I can access all the features for signed-up users.**

## Acceptance Criteria

- Users can register with a unique username and a password.

## Tasks

- [x] - Create sign up link on NavBar
- [x] - Create a sign-up form
- [x] - Create redirect so successful sign-up will redirect to sign in form

## Epic

Authentication - #3
