### ISSUE TITLE
User Story: Authentication | Sign in

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#12]
As a **user** I can **sign in to the app** so that **I can access functionality for logged-in users.**

## Acceptance Criteria

- Users can sign in using the credentials they used to sign up.

## Tasks

- [x] - Create a sign-in link on NavBar
- [x] - Create a sign-in form
- [x] - Create a redirect so that successful sign-in will redirect to the home page

## Epic

Authentication - #3
