### ISSUE TITLE
User Story: Authentication | Logged in Status

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#13]
As a **user** I can **tell if I am logged in or not** so that **I can log in if I need to.**

## Acceptance Criteria

- The login status indicator should be visible on all pages of the website, including the homepage and all subpages.
- If the user enters invalid login credentials, they should be informed of the error and allowed to try again.

## Tasks

- [x] - Send an API request to check who the currently logged in user is.
- [x] - Check what icons do display based on the currentUser value.
- [x] - Use the useContext hook.

## Epic

Authentication - #3
