### ISSUE TITLE
User Story: Authentication | Refreshing access tokens

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#14]
As a **user** I can **maintain my logged-in status until I choose to log out** so that **my user experience is not compromised.**

## Acceptance Criteria

- The user should be able to remain logged in for an extended period of time without having to log in again, unless they choose to log out.

## Tasks

- [x] - Create axios interceptors axiosRes and axiosReq.
- [x] - Set axiosRes to refresh access_token if it gets a 401 error.
- [x] -  Add axiosRes to handleMount
- [x] - Set axiosReq to always refresh access token before making a request.

## Epic

Authentication - #3
