### ISSUE TITLE
User Story: Navigation: Conditional rendering

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#15]
As a **logged out user** I can **see sign-in and sign-up options** so that **I can sign in/sign up**

## Acceptance Criteria

- When a user is logged out, the navigation bar should display the "Sign In" and "Sign Up" options prominently, in a clear and easily recognizable way.
- Clicking on either the "Sign In" or "Sign Up" options should redirect the user to the appropriate page to complete the corresponding action.

## Tasks

- [x] - Create Nav Links for Feed, Liked and Sign Out options.
- [x] - Create Avatar for profile picture.
- [x] - Create handle function to sign out button.

## Epic
Navigation - #2
