### ISSUE TITLE
User Story: Create posts

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#16]
As a **logged-in user** I can **create posts** so that **I can share my images with everyone.**

## Acceptance Criteria

- When a user is logged in, they should be able to access a "Create Post" option from the navigation bar or dashboard, which should redirect them to a page where they can create a post.
- The "Create Post" page should allow the user to upload images and input accompanying text for their post. The user should be able to preview their post before publishing it.
- After the user has created a post, it should be displayed publicly on the platform, with the image and accompanying text visible to all users. The post should also include information such as the date/time of the post and the username of the user who created it.

## Tasks

- [x] - Create post edit form module css and Asset css.
- [x] - Create Post create components.
- [x] - Send Post data to the API

## Epic

Adding & Liking Posts - #4
