### ISSUE TITLE
User Story: Like a post

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#18]
As a **logged-in user** I can **like a post** so that **I can show my support for the posts that interest me.**

## Acceptance Criteria

- When a user is logged in and views a post, there should be a visible "Like" button on the posting page with an icon of Ray.
- When the user clicks on the "Like" button, the number of likes associated with the post should increase by one, and the button should be visually updated to indicate that the user has liked the post ( change the colour of the icon).
- The system should prevent a user from liking a post more than once, and the "Like" icon should not work for users who are not logged in.

## Tasks

- [x] - Create handleLike function to allow users to like posts.
- [x] - Create handleUnlike function o allow users to unlike posts.
- [x] - Add icons to button like.

## Epic

Adding & Liking Posts - #4
