### ISSUE TITLE
User Story: View most recent posts

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#19]
As a **user** I can **view all the most recent posts, ordered by most recently created first** so that **I am up to date with the newest content.**

## Acceptance Criteria

- The user should be able to access a designated section/page that displays all the most recent posts, ordered by the most recently created first.
- The content of the posts should include at least the title, the house of Hogwarts and the creation date.

## Tasks

- [x] - Create posts page component.
- [x] - Create posts page module css.
- [x] - Display an array of posts using filters.

## Epic

The Posts Page - #5
