### ISSUE TITLE
User Story: Search Posts

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#20]
As **a user**, I can **search for posts with keywords,** so that **I can find the posts and user profiles I am most interested in.**

## Acceptance Criteria

- The user should be able to enter one or more keywords into a search bar and initiate a search to find relevant posts.
- The search should be case-insensitive and should match both post titles and content.
- The search results page should display relevant posts in a clear and organized manner.

## Tasks

- [x] - Add search bar to post component.
- [x] - Add text search with filters and keywords.
- [x] - Add timer to loading for searching for keywords.

## Epic

The Posts Page - #5
