### ISSUE TITLE
User Story: Delete comments

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#29]
As an **owner of a comment** I can **delete my comment** so that **I can control the removal of my comment from the application.**

## Acceptance Criteria

- The comment owner should be able to access an interface that allows them to delete their comment from a specific post.
- The comment should be immediately removed from the posting page and any associated views or feeds once it has been successfully deleted.

## Tasks

- [x] - Create handle edit comment function.
- [x] - Decrement post's count by one.
- [x] - Filter out the deleted comment from the array.

## Epic

The Post Page - #6
