### ISSUE TITLE
User Story: Profile page

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#31]
As a **user** I can **view other users' profiles** so that **I can see their posts and learn more about them.**

## Acceptance Criteria

- The profile page should display the user's name, profile picture, bio, numbers of the posts, followers and following of the user's profile.
- The user should be able to view the other user's posts on their profile page.
- 

## Tasks

- [x] - Create profile page component.
- [x] - Create profile page css.
- [x] - Create Route profile page by its id.
- [x] - Create follow/unfollow buttons.

## Epic

The Profile Page - #7
