### ISSUE TITLE
User Story: Follow/Unfollow a user

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#34]
As a **logged-in** user I can **follow and unfollow other users** so that **I can see and remove posts by specific users in my posts feed.**

## Acceptance Criteria

- The user should be able to follow any other user by clicking on a "follow" button on their profile or on their posts.
- The user should be able to unfollow any user they are currently following by clicking on an "unfollow" button on the user's profile.
- The user's posts feed should update in real-time to display or remove posts from the users they follow or unfollow.

## Tasks

- [x] - Create a handle follow async function.
- [x] - Create a handle unfollow async function.
- [x] - Create a helper function.

## Epic

The Profile Page - #7
