### ISSUE TITLE
User Story: Edit profile

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#36]
As a **logged-in user** I can **edit my profile** so that **I can change my profile picture and bio.**

## Acceptance Criteria

- The user should be able to edit their profile picture and bio by clicking on an "edit profile" button on their profile page.
- The user should be able to upload a new profile picture from their device or choose an existing picture from their photo library.
- The user should be able to modify their bio by typing in a text field.

## Tasks

- [x] - Create profile edit form.
- [x] - Create profile edit module css.
- [x] - Add dropdown menu.

## Epic

The Profile Page - #7
