### ISSUE TITLE
User Story: Update username and password

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#37]
As a **logged-in user** I can **update my username and password** so that **I can change my display name and keep my profile secure.**

## Acceptance Criteria

- The user should be able to update their username and password by clicking on an "update profile" button on their profile page.
- The user should be able to change their username to a unique name that is not already taken by another user.
- The user should be able to update their password by entering their current password and then entering and confirming a new password that meets the system's password complexity requirements.

## Tasks

- [x] - Create username form.
- [x] - Create password form.
- [x] - Create router for both.

## Epic

The Profile Page - #7
