### ISSUE TITLE
User Story: Navigation

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/hogwarts#9]
As a **user** I can **view a navbar from every page** so that **I can navigate easily between pages.**

## Acceptance Criteria

- The navigation bar should be visible on every page and inform users of their current location in the site structure.
- The navigation bar should present a different layout suited to the screen size it is being viewed from.

## Tasks

- [x] - Create NavBar component
- [x] - Configure basic site routing
- [x] - Make NavBar responsive for smaller screens

## Epic

Navigation - #2
